version: '3.8'

services:
  nakama:
    image: heroiclabs/nakama:3.17.0
    container_name: nakama_backend
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - >
        /nakama/nakama migrate up --database.address "postgresql://bhupi:xkgZ6bLb4xuYDGMfq9hZNg@dust-fish-18126.j77.aws-ap-south-1.cockroachlabs.cloud:26257/defaultdb?sslmode=verify-full" &&
        exec /nakama/nakama --name nakama1 --database.address "postgresql://bhupender:yourpassword@free-tier14.aws-ap-south-1.cockroachlabs.cloud:26257/defaultdb?sslmode=verify-full" --logger.level info
    ports:
      - "7349:7349"
      - "7350:7350"
      - "7351:7351"
    restart: unless-stopped
