version: '3.8'

services:
  postgres:
    image: postgres:12.2-alpine
    container_name: template_nk_postgres
    restart: always
    environment:
      POSTGRES_DB: nakama
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: localdb
    ports:
      - '5432:5432'
    volumes:
      - data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d nakama']
      interval: 5s
      timeout: 5s
      retries: 5

  nakama:
    build: .
    container_name: template_nk_backend
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint:
      - '/bin/sh'
      - '-ecx'
      - >
        /nakama/nakama migrate up --database.address postgres:localdb@postgres:5432/nakama?sslmode=disable &&
        exec /nakama/nakama --config /nakama/data/local.yml --database.address postgres:localdb@postgres:5432/nakama?sslmode=disable --logger.level info --session.token_expiry_sec 7200
    ports:
      - '7349:7349'
      - '7350:7350'
      - '7351:7351'
    restart: unless-stopped
    volumes:
      - .:/nakama/data

volumes:
  data:
